config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  get 'welcome/index'

  resources :users

  resources :rweets do
    resources :likes
    resources :comments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'

  get 'logout' => 'sessions#destroy'
  get 'home' => 'rweets#index'
  get ':username' => 'users#show'
  delete 'post/:id' => 'rweets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to  :rweet, dependent: :destroy
  belongs_to  :parent, class_name: 'Comment', optional: true
  has_many    :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

  validates :body, presence: :true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :rweet
  belongs_to :user
end

app/models/rweet.rb
class Rweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  has_many :rweets
  has_many :likes, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || home_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :description, :first_name , :last_name, :location])
    devise_parameter_sanitizer.permit(:account_update , keys: [:description,:location])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @rweet = Rweet.find(params[:rweet_id])
    @comment = @rweet.comments.new(parent_id: params[:parent_id])
  end


  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @rweet = Rweet.find(params[:rweet_id])
    @comment = @rweet.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @rweet }
      end
    end
  end


  # PATCH/PUT /comments/1 or /comments/1.json
    def update
      respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
          format.json { render :show, status: :ok, location: @comment }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /comments/1 or /comments/1.json
    def destroy
      @comment.destroy

      respond_to do |format|
        format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :rweet_id, :parent_id)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_rweet
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @rweet.likes.create(user_id: current_user.id)
    end
    redirect_to rweet_path(@rweet)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to rweet_path(@rweet)
  end

  def find_like
    @like = @rweet.likes.find(params[:id])
  end

  private
  def find_rweet
    @rweet = Rweet.find(params[:rweet_id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, rweet_id:
      params[:rweet_id]).exists?
  end
end

app/controllers/rweets_controller.rb
class RweetsController < ApplicationController
  before_action :authenticate_user!, only: %i[create new destroy update]
  protect_from_forgery with: :null_session

  def index
    @rweets = Rweet.all
  end

  def show
    @rweet = Rweet.find(params[:id])
  end

  def new
    @rweet = Rweet.new
  end

  def create
    @rweet = Rweet.new(rweet_params)
    @rweet.user_id = current_user.id
    if @rweet.save
      redirect_to '/rweets#index'
    else
      render 'new'
    end
  end

  def destroy
    @rweet = Rweet.find(params[:id])
    @rweet.destroy
    redirect_to root_path, :notice => "Your rweet has been deleted"
  end

  private
  def rweet_params
    params.require(:rweet).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    session.destroy
    # Delete cookie to log out even with remember me
    cookies.delete :remember_user_token
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.where('lower(username) = ?', params[:username]).first || User.find_by_username(params[:username])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rweets_helper.rb
module RweetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/axentix@2.0.1/dist/axentix.min.css">
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>


<div id="<%= dom_id comment %>">
  <% unless comment.parent_id || !comment.persisted? %>

    <div class="post">
      <div class="post_avatar">
        <%= image_tag("profile.png", alt: "Example Image", class: "img") %>
      </div>

      <div class="post_body">
        <div class="post_header">
          <div class="post_header_text">
            <h3><%= User.find(Rweet.find(comment.rweet_id).user_id).username %>
              <span class="post_header_special">
              <span class="material-symbols-outlined post_badge"> verified </span>@michel  <%= time_ago_in_words(comment.created_at) %>
            </span>
            </h3>
          </div>
          <div class="post_header_description">
            <p><%= comment.body %></p>
          </div>
        </div>
      </div>
    </div>

  <% end %>


  <%#= link_to 'reply', new_rweet_comment_path(@rweet, parent_id: comment.id), remote: true, class: 'd-block' %>
  <%# if comment.replies.any? %>
    <%# comment.replies.each do |reply| %>
      <%#= render partial: 'comments/reply', locals: { reply: reply } %>
    <%# end %>
  <%# end %>
<!--  <div id="reply-form-<%#= comment.id %>"></div>-->

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :rweet_id, style: "display: block" %>
    <%= form.number_field :rweet_id %>
  </div>

  <div>
    <%= form.label :parent_id, style: "display: block" %>
    <%= form.number_field :parent_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_reply.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= reply.body %>
  </div>
</div>

app/views/comments/_reply_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_with(model: [@rweet, @comment]) do |f| %>
      <%= f.hidden_field :parent_id %>
      <div class="form-group">
        <%= f.label 'Reply' %>
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', rweet_path(@rweet), class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/new.js.erb
document.querySelector("#reply-form-<%= @comment.parent_id %>").innerHTML = ("<%= j render 'reply_form', comment: @comment %>")

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/rweets/edit.html.erb
<h1>Editing rweet</h1>

<%= render "form", rweet: @rweet %>

<br>

<div>
  <%= link_to "Show this rweet", @rweet %> |
  <%= link_to "Back to rweets", rweets_path %>
</div>

app/views/rweets/index.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/axentix@2.0.1/dist/axentix.min.css">
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>

<p style="display: none"><%= notice %></p>

<!-- beginning of sidebar -->

<body style="background-color: #111;position: relative;left: 300px;">
<div class="sidebar">
  <%= image_tag("rwitter-logo.png", size: "40x40", style: "position: relative;left: 16px;") %>

  <%= link_to rweets_path do %>
    <div class="sidebarOption active">
      <span class="material-symbols-outlined"> home </span>
      <h2><span>Home</span></h2>
    </div>
  <% end %>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> search </span>
    <h2>Explore</h2>
  </div>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> notifications_none </span>
    <h2>Notification</h2>
  </div>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> mail_outline </span>
    <h2>Messages</h2>
  </div>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> bookmark_border </span>
    <h2>Bookmarks</h2>
  </div>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> list_alt </span>
    <h2>Lists</h2>
  </div>

  <%= link_to url_for(root_url+current_user.username) do %>
    <div class="sidebarOption active">
      <span class="material-symbols-outlined"> perm_identity </span>
      <h2><span>Profile</span></h2>
    </div>
  <% end %>

  <%= link_to logout_path do %>
    <div class="sidebarOption active">
      <span class="material-symbols-outlined"> more_horiz </span>
      <h2><span>Log Out</span></h2>
    </div>
  <% end %>

  <%= link_to new_rweet_path do %>
    <button class="sidebar-rweet">Rweet </button>
  <% end %>

</div>


<div class="feed">

  <div class="feed_header">
    <h2>Home</h2>
  </div>

  <div class="rweet-box">
    <form>
      <div class="rweetbox-input">
        <%= image_tag("profile.png", alt: "Example Image", class:"img") %>
<!--        <span class="material-symbols-outlined"> account_circle </span>-->

            <input type="text" placeholder="What's new?" style="padding-left: 5px;">


        <%#= render "form", rweet: @rweet %>

      </div>
      <button class="rweet-box--rweet-button">Rweet</button>
    </form>
  </div>

  <% @rweets.each do |rweet| %>

    <div class="post">
      <div class="post_avatar">
        <%= image_tag("profile.png", alt: "Example Image", class:"img") %>
      </div>

      <div class="post_body">
        <div class="post_header">
          <div class="post_header_text">
            <h3><%= User.find(rweet.user.id).username %>
              <span class="post_header_special">
              <span class="material-symbols-outlined post_badge"> verified </span>@michel  <%= time_ago_in_words(rweet.created_at) %>
            </span>
            </h3>
          </div>
          <div class="post_header_description">
            <p><%= rweet.body %></p>
          </div>
        </div>

        <div class="post_footer">
          <span class="material-symbols-outlined"> repeat </span>
          <%= rweet.likes.count %><span class="material-symbols-outlined"> <%#= (rweet.likes.count) <= 1 ? 'Like' : 'Likes' %> favorite_border </span>
          <span class="material-symbols-outlined"> publish </span>
        </div>
      </div>
      <%= link_to "See More", rweet_path(rweet.id), :method => :get,style: "position: relative;top: 30px;right: 190px;text-decoration: underline;" %>
    </div>

<% end %>

  <div class="post">
    <div class="post_avatar">
      <%= image_tag("profile.png", alt: "Example Image", class:"img") %>
    </div>

    <div class="post_body">
      <div class="post_header">
        <div class="post_header_text">
          <h3>Michel
            <span class="post_header_special">
              <span class="material-symbols-outlined post_badge"> verified </span>@michel
            </span>
          </h3>
        </div>
        <div class="post_header_description">
          <p>After selling Twitter to Elon Musk he gave me this Tesla !</p>
        </div>
      </div>

      <%= image_tag("car.jpg", alt: "Example Image", class:"img") %>

      <div class="post_footer">
        <span class="material-symbols-outlined"> repeat </span>
        <span class="material-symbols-outlined"> favorite_border </span>
        <span class="material-symbols-outlined"> publish </span>
      </div>
    </div>
  </div>

</div>
</body>

app/views/rweets/new.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/axentix@2.0.1/dist/axentix.min.css">
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>

<body style="background-color: #111;position: relative;left: 300px;">
<div class="sidebar">
  <%= image_tag("rwitter-logo.png", size: "40x40", style: "position: relative;left: 16px;") %>

  <%= link_to rweets_path do %>
    <div class="sidebarOption active">
      <span class="material-symbols-outlined"> home </span>
      <h2><span>Home</span></h2>
    </div>
  <% end %>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> search </span>
    <h2>Explore</h2>
  </div>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> notifications_none </span>
    <h2>Notification</h2>
  </div>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> mail_outline </span>
    <h2>Messages</h2>
  </div>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> bookmark_border </span>
    <h2>Bookmarks</h2>
  </div>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> list_alt </span>
    <h2>Lists</h2>
  </div>

  <%= link_to url_for(root_url+current_user.username) do %>
    <div class="sidebarOption active">
      <span class="material-symbols-outlined"> perm_identity </span>
      <h2><span>Profile</span></h2>
    </div>
  <% end %>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> more_horiz </span>
    <h2>More</h2>
  </div>


  <%= button_to "Rweet", new_rweet_path, :class => "sidebar-rweet" %>


</div>


<div class="feed">
  <div class="feed_header">
    <h2>Send a new Rweet now !</h2>
  </div>


  <div class="rweet-box">

      <div class="rweetbox-input">
        <%= image_tag("profile.png", alt: "Example Image", class: "img") %>
        <%= render "form", rweet: @rweet %>

      </div>

  </div>

</div>
</body>

app/views/rweets/show.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/axentix@2.0.1/dist/axentix.min.css">
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>

<body style="background-color: #111;position: relative;left: 300px;">
<div class="sidebar">

  <%= image_tag("rwitter-logo.png", size: "40x40", style: "position: relative;left: 16px;") %>

  <%= link_to rweets_path do %>
    <div class="sidebarOption active">
      <span class="material-symbols-outlined"> home </span>
      <h2><span>Home</span></h2>
    </div>
  <% end %>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> search </span>
    <h2>Explore</h2>
  </div>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> notifications_none </span>
    <h2>Notification</h2>
  </div>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> mail_outline </span>
    <h2>Messages</h2>
  </div>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> bookmark_border </span>
    <h2>Bookmarks</h2>
  </div>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> list_alt </span>
    <h2>Lists</h2>
  </div>

  <%= link_to url_for(root_url + current_user.username) do %>
    <div class="sidebarOption active">
      <span class="material-symbols-outlined"> perm_identity </span>
      <h2><span>Profile</span></h2>
    </div>
  <% end %>

  <div class="sidebarOption active">
    <span class="material-symbols-outlined"> more_horiz </span>
    <h2>More</h2>
  </div>


  <%= button_to "Rweet", new_rweet_path, :class => "sidebar-rweet" %>

</div>

<div style="width: 60%">

  <%= render @rweet %>

  <% pre_like = @rweet.likes.find { |like| like.user_id == current_user.id } %>
  <% if pre_like %>
    <%= button_to 'Unlike', rweet_like_path(@rweet, pre_like), method: :delete, :class => "sidebar-rweet"  %>
  <% else %>
    <%= button_to 'Like', rweet_likes_path(@rweet), method: :post , :class => "sidebar-rweet" %>
  <% end %>

  <% if current_user == @rweet.user %>
    <%= button_to "Destroy this rweet", @rweet, method: :delete, :class => "sidebar-rweet" %>
  <% end %>

  <div>
    <div>
      <p>Comments</p>
      <%= form_with(model: [@rweet, @rweet.comments.build]) do |f| %>
        <div>
          <%= f.label 'New comment' %>
          <%= f.text_area :body, class: 'form-control rounded-1' %>
        </div>
        <%= f.submit 'Comment', class: 'rweet-box--rweet-button sidebar-rweet' %>
        <p style="color: green"><%= notice %></p>
      <% end %>
    </div>
  </div>

  <%= render @rweet.comments %>
</div>
</body>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/axentix@2.0.1/dist/axentix.min.css">
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>

<% if @user.nil? %>
  No user found with this name.
<% else %>
  <body style="background-color: #111;position: relative;left: 300px;">
  <div class="sidebar">
    <%= image_tag("rwitter-logo.png", size: "40x40", style: "position: relative;left: 16px;") %>

    <%= link_to rweets_path do %>
      <div class="sidebarOption active">
        <span class="material-symbols-outlined"> home </span>
        <h2><span>Home</span></h2>
      </div>
    <% end %>

    <div class="sidebarOption active">
      <span class="material-symbols-outlined"> search </span>
      <h2>Explore</h2>
    </div>

    <div class="sidebarOption active">
      <span class="material-symbols-outlined"> notifications_none </span>
      <h2>Notification</h2>
    </div>

    <div class="sidebarOption active">
      <span class="material-symbols-outlined"> mail_outline </span>
      <h2>Messages</h2>
    </div>

    <div class="sidebarOption active">
      <span class="material-symbols-outlined"> bookmark_border </span>
      <h2>Bookmarks</h2>
    </div>

    <div class="sidebarOption active">
      <span class="material-symbols-outlined"> list_alt </span>
      <h2>Lists</h2>
    </div>

    <%= link_to url_for(root_url+current_user.username) do %>
      <div class="sidebarOption active">
        <span class="material-symbols-outlined"> perm_identity </span>
        <h2><span>Profile</span></h2>
      </div>
    <% end %>

    <%= link_to logout_path do %>
      <div class="sidebarOption active">
        <span class="material-symbols-outlined"> more_horiz </span>
        <h2><span>Log Out</span></h2>
      </div>
    <% end %>

    <%= link_to new_rweet_path do %>
      <button class="sidebar-rweet">Rweet </button>
    <% end %>

  </div>

  <div class="feed">

    <div class="feed_header">
      <span class="material-symbols-outlined" style="position: relative;top: 3px;right: 15px;">arrow_back</span><span style="font-size: 24px"><%= @user.username %></span><br>
    </div>
    <div>
      <%= image_tag("/images/banner.png", size: "619x199") %>
    </div>
    <div class="grix xs3" style="height: 75px;">
      <div class="logo"><% if @user.id > 2 %> <%= image_tag("/images/avatar_logo_2.png", size: "150x150", :style => "border-radius: 50%;position: relative;top: -95px;border: 5px solid black;left: 50px;") %> <% else %><%= image_tag("/images/avatar_logo_#{@user.id}.png", size: "150x150", :style => "border-radius: 50%;position: relative;top: -95px;border: 5px solid black;left: 50px;") %><% end %></div>
      <div class="logo-right col-xs2" >
        <% if @user.username == current_user.username %><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link btn rounded-4 white btn-press' , style: "style=font-size: 16px;position: relative;right: -250px;top: 10px;"%><% end %></div>
    </div>

    <div style="position: relative;left: 35px;top:-12px;">
      <span style="font-weight: bold;font-size: 21px;"><%= @user.username %></span><br>
      @<%= @user.username.downcase %>
    </div>

    <div  style="position: relative;left: 35px;">
      <% if @user.description == nil %>
        <%= "No description" %>
      <% else %>
        <%= @user.description %>
      <% end %>
    </div>

    <div  style="position: relative;left: 35px;">
      <% if @user.location == nil %>
        <span class="material-symbols-outlined" style="position: relative;top: 4px;">apartment </span><%= "No location" %>
      <% else %>
        <span class="material-symbols-outlined" style="position: relative;top: 4px;">apartment </span> City: <%= @user.location %>
      <% end %>
      <% if @user.confirmed_at != nil %>
        <span class="material-symbols-outlined" style="position: relative;top: 4px;">calendar_month </span> Joined Twitter in <%= @user.confirmed_at.to_formatted_s(:month_and_year) %>
      <% end %>
    </div>
    <div style="border: 1px solid var(--rwitter-background);position: relative;top: 10px;"></div>

    <% @user.rweets.each do |rweet| %>
      <div class="post">
        <div class="post_avatar">
          <%= image_tag("profile.png", alt: "Example Image", class:"img") %>
        </div>

        <div class="post_body">
          <div class="post_header">
            <div class="post_header_text">
              <h3><%= User.find(rweet.user.id).username %>
                <span class="post_header_special">
              <span class="material-symbols-outlined post_badge"> verified </span>@michel  <%= time_ago_in_words(rweet.created_at) %>
            </span>
              </h3>
            </div>
            <div class="post_header_description">
              <p><%= rweet.body %></p>
            </div>
          </div>

          <div class="post_footer">
            <span class="material-symbols-outlined"> repeat </span>
            <%= rweet.likes.count %><span class="material-symbols-outlined">favorite_border </span>
            <span class="material-symbols-outlined"> publish </span>
          </div>
        </div>
        <%= link_to "See More", rweet_path(rweet.id), :method => :get, style: "position: relative;top: 30px;right: 230px;text-decoration: underline;" %>
      </div>
    <% end %>

  </div>
  </body>
<% end %>

app/views/welcome/index.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/axentix@2.0.1/dist/axentix.min.css">

<body style="background-color: black; overflow: hidden">

<div class="display-flex">
  <% if user_signed_in? %>
    <h1>Hello, <%= current_user.username %> !</h1>
    <%= link_to 'Profile', url_for(root_url + current_user.username), :class => 'navbar-link' %> |
    <%= link_to "Log out", logout_path, method: :delete, :class => 'navbar-link' %>
  <% else %>
    <div class="image">
      <%= image_tag("acceuiltwitter.jpg", alt: "Example Image", class: "image") %>
    </div>
    <div class="title">
      <h1 class="text-end">Ça se passe maintenant</h1>
      <h3 class="text-endend">Rejoignez Rwitter dès aujourd'hui.</h3>
      <%= link_to "Sign up", new_user_registration_path, :class => 'btn rounded-1 blue btn-press' %>
      <%= link_to "Login", new_user_session_path, :class => 'btn rounded-1 blue btn-press' %>
    </div>
    <div class="twitter">
      <%= image_tag("rwitter-logo.png", alt: "Example Image", class: "twitter") %>
    </div>
    <div class="twitter2">
      <%= image_tag("twitter2.jpg", alt: "Example Image", class: "twitter2") %>
    </div>
    </div>
  <% end %>
  </body>